# Generated by Django 6.0.4 on 2026-04-23 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0002_category_city_place_review_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='itineraries.place'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='service_type',
            field=models.CharField(choices=[('transportation', 'Transportation'), ('guide', 'Guide'), ('hotel', 'Hotel'), ('food', 'Food'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
