from django.urls import path

from .views import (
    BookingDetailView,
    BookingListCreateView,
    CategoryDetailView,
    CategoryListCreateView,
    CategoryListView,
    CityDetailView,
    CityListCreateView,
    CityListView,
    ItineraryDetailView,
    ItineraryItemDetailView,
    ItineraryItemListCreateView,
    ItineraryListCreateView,
    PlaceDetailView,
    PlaceDiscoveryView,
    PlacePublicDetailView,
    PlaceListCreateView,
    PlaceReviewListCreateView,
    ReviewDetailView,
    ReviewListView,
    ServiceRequestDetailView,
    ServiceRequestListCreateView,
    TicketDetailView,
    TicketListView,
    UserReviewDetailView,
)

urlpatterns = [
    path('', ItineraryListCreateView.as_view(), name='itinerary-list-create'),
    path('<int:pk>/', ItineraryDetailView.as_view(), name='itinerary-detail'),
    path('categories/', CategoryListView.as_view(), name='category-list'),
    path('cities/', CityListView.as_view(), name='city-list'),
    path('places/', PlaceDiscoveryView.as_view(), name='place-discovery'),
    path('places/<int:pk>/', PlacePublicDetailView.as_view(), name='place-public-detail'),
    path('places/<int:place_pk>/reviews/', PlaceReviewListCreateView.as_view(), name='place-review-list-create'),
    path('reviews/<int:pk>/', UserReviewDetailView.as_view(), name='user-review-detail'),
    path('service-requests/', ServiceRequestListCreateView.as_view(), name='service-request-list-create'),
    path('service-requests/<int:pk>/', ServiceRequestDetailView.as_view(), name='service-request-detail'),
    path('bookings/', BookingListCreateView.as_view(), name='booking-list-create'),
    path('bookings/<int:pk>/', BookingDetailView.as_view(), name='booking-detail'),
    path('<int:itinerary_pk>/items/', ItineraryItemListCreateView.as_view(), name='itinerary-item-list-create'),
    path('<int:itinerary_pk>/items/<int:pk>/', ItineraryItemDetailView.as_view(), name='itinerary-item-detail'),
    path('admin/categories/', CategoryListCreateView.as_view(), name='category-list-create'),
    path('admin/categories/<int:pk>/', CategoryDetailView.as_view(), name='category-detail'),
    path('admin/cities/', CityListCreateView.as_view(), name='city-list-create'),
    path('admin/cities/<int:pk>/', CityDetailView.as_view(), name='city-detail'),
    path('admin/places/', PlaceListCreateView.as_view(), name='place-list-create'),
    path('admin/places/<int:pk>/', PlaceDetailView.as_view(), name='place-detail'),
    path('admin/reviews/', ReviewListView.as_view(), name='review-list-create'),
    path('admin/reviews/<int:pk>/', ReviewDetailView.as_view(), name='review-detail'),
    path('admin/tickets/', TicketListView.as_view(), name='ticket-list-create'),
    path('admin/tickets/<int:pk>/', TicketDetailView.as_view(), name='ticket-detail'),
]
