# Generated by Django 6.0.4 on 2026-04-23 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_place_placegallery_savedplace'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('itinerary_id', models.AutoField(primary_key=True, serialize=False)),
                ('trip_name', models.CharField(max_length=255)),
                ('trip_type', models.CharField(blank=True, choices=[('Solo Travel', 'Solo Travel'), ('Family', 'Family'), ('Business', 'Business'), ('Honeymoon', 'Honeymoon')], max_length=50, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('cover_image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('quick_notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Upcoming', 'Upcoming'), ('Current', 'Current'), ('Completed', 'Completed'), ('Archived', 'Archived')], default='Draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItineraryItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('day_number', models.IntegerField(default=1)),
                ('sequence_order', models.IntegerField(default=0)),
                ('arrival_time', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.itinerary')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_appearances', to='api.place')),
            ],
            options={
                'ordering': ['day_number', 'sequence_order'],
            },
        ),
    ]
