# Generated by Django 6.0.4 on 2026-05-20 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_supportticket'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='passwordresetotp',
            new_name='api_passwor_code_7e1112_idx',
            old_name='api_pa_code_f54590_idx',
        ),
    ]
