# Generated by Django 6.0.4 on 2026-05-28 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
